from flask import Flask, render_template, request, jsonify
import random

app = Flask(__name__)

user_hi = [
    "Hi", "Hello", "Hey", "Hi there", "Hi, how are you?", "What's up?", 
    "How do you do?", "How are you?", "How are you doing?", "What's going on?", 
    "Hi, what's new?", "How are things?", "Hey, anything interesting happening?", 
    "How’s your day going?", "Hi there, how have you been?", "What's up with you?", 
    "Hi, are you available to chat?", "How's everything on your end?", 
    "Hi, do you have a moment?", "Hey, how have you been feeling?", 
    "What's happening?", "Is everything good?", "Have you been okay?", 
    "Hi, is this a good time?", "Hi, can we talk?", "Hey, how’s life?", 
    "Hello, how’s everything?", "What's going on today?", "Hey, got time to talk?", 
    "Hey, been busy?", "Hello, got any news?", "Hi, how’s work going?", 
    "Hi, how’s the family?", "Hi, anything new?", "Hey, what’s the latest?", 
    "Hi, been up to anything fun?", "Hey, long time no chat!", 
    "How’s it going on your end?", "Hi, feeling okay today?", 
    "Hey, what’s happening?", "Hello, what have you been doing?", 
    "What’s up with you lately?", "Hi, have you been productive?", 
    "Hey, what’s up in your world?", "Hi, been traveling?", 
    "Hello, doing anything fun today?", "Hi, do you have plans today?", 
    "Hey, what's your day like?", "Hi, are you free?", "Hey, feeling good?", 
    "Hello, have you been working hard?", "Hey, are you around?", 
    "Hi, can we catch up?", "Hello, any big news?", "What’s up with your life?", 
    "Hello, did anything exciting happen?", "Hey, how’s the weekend going?", 
    "Hi, have you been out?", "What’s up, anything interesting?", 
    "Hey, did something cool happen?", "Hi, are you keeping busy?", 
    "Hey, do you have some free time?", "Hello, got any plans today?", 
    "Hi, are you doing well?", "What’s new with you?", 
    "Hey, has anything interesting happened?", "Hello, did you have a good day?", 
    "Hey, have you been resting enough?", "Hi, what’s your plan for the day?", 
    "What’s happening today?", "Hey, are you doing anything fun?", 
    "Hi, been working hard?", "Hello, are you keeping up with things?", 
    "What’s up, any exciting plans?", "Hi, how’s everything going?", 
    "Hey, how are things on your end?", "What’s going on in your world?", 
    "Hello, anything good happening?", "Hi, have you been relaxing?", 
    "Hey, has your day been okay?", "Hi, anything fun planned?", 
    "Hello, been enjoying life?", "Hey, how’s work treating you?", 
    "Hi, are you feeling stressed?", "What’s up, been busy?", 
    "Hello, have you been traveling?", "Hey, how’s your family doing?", 
    "Hi, any good news?", "Hey, what’s been keeping you busy?", 
    "What’s up, did you finish your tasks?", "Hello, have you been socializing?", 
    "Hi, did you finish your project?", "What’s up, anything new to report?", 
    "Hey, how’s your mood today?", "Hello, are you free to chat?", 
    "What’s happening in your life?", "Hi, did you achieve your goals today?", 
    "Hey, what’s your next big thing?"
]


Chatbot_hi = [
    "Hi", "Hello", "Hey", "Hi there", "Hi, how are you?", "What's up?", 
    "How do you do?", "How are you?", "How are you doing?", "What's going on?", 
    "Hey, I'm doing great!", "Hello, I’m here!", "Hi there, how can I help?", 
    "Hey, need assistance?", "I'm here, how can I help you?", 
    "Hi, what’s your question?", "Hello, I’m ready to chat!", 
    "Hey, ready when you are!", "Hi, I'm doing well!", "Hello, how can I assist?", 
    "Hey, feeling helpful today!", "Hi, what can I do for you?", 
    "Hello, need something?", "Hey, I'm all ears!", 
    "Hi there, what’s on your mind?", "Hi, I’m here to assist you!", 
    "Hello, got a question?", "Hey, tell me what you need!", 
    "Hi, need help with something?", "Hello, how can I be of service?", 
    "Hey, I’m ready to help!", "Hello, ready for your questions!", 
    "Hey, what do you want to know?", "Hi, how can I assist you today?", 
    "Hey, what’s your inquiry?", "Hi, got a query for me?", 
    "Hello, I’m feeling helpful!", "Hi there, anything I can do for you?", 
    "Hey, what’s up?", "Hi, I’m here to answer your questions!", 
    "Hello, got anything on your mind?", "Hi, how can I assist you?", 
    "Hey, need advice?", "Hello, what’s your question?", 
    "Hey, feel free to ask!", "Hi, how can I help you today?", 
    "Hello, need anything?", "Hey, I’m ready to help!", 
    "Hi there, what’s your question?", "Hello, what do you need assistance with?", 
    "Hi, feel free to ask anything!", "Hey, I’m here to answer!", 
    "Hello, what can I do for you today?", "Hi, tell me what you’re thinking!", 
    "Hello, need guidance?", "Hey, I’ve got answers!", 
    "Hi, I’m happy to help!", "Hello, tell me what you need!", 
    "Hey, ready when you are!", "Hi, I’m here for your questions!", 
    "Hello, ask me anything!", "Hey, need to know something?", 
    "Hi, I’m ready to chat!", "Hello, got a question for me?", 
    "Hey, I’m here to assist you!", "Hi, what can I answer for you?", 
    "Hello, I’m feeling helpful today!", "Hey, ask away!", 
    "Hi, I’m here to solve your queries!", "Hello, what can I help you with?", 
    "Hey, I’m listening!", "Hi, I’m here to chat!", 
    "Hello, got a problem I can solve?", "Hey, I’m ready to chat!", 
    "Hi, let’s chat!", "Hello, need my help?", "Hey, what’s on your mind?", 
    "Hi, I’m all set to help!", "Hello, ask me anything!", 
    "Hey, I’m here for you!", "Hi, I’ve got the answers you need!", 
    "Hello, tell me what you’re thinking about!", "Hey, what’s your query?", 
    "Hi, ready to assist you!", "Hello, what’s your question?", 
    "Hey, what can I do for you?", "Hi, tell me what’s on your mind!", 
    "Hello, I’m ready to help!", "Hey, how can I assist you?", 
    "Hi, got any questions for me?", "Hello, feel free to ask!"
]

general_answers = [
    "I'm doing well!", "I'm well!", "I'm great!", "I'm good!", "I'm doing okay!", 
    "I'm okay!", "I've been busy!", "I could be worse!", "I'm fantastic!", 
    "Not too bad!", "Things are looking up!", "I'm feeling good!", 
    "All is well!", "I've had better days.", "I'm hanging in there.", 
    "I'm managing.", "I'm getting by.", "It's been a tough day.", 
    "I've been better.", "Today’s a bit rough.", "I’m in a good mood!", 
    "Not the best day.", "I'm feeling positive!", "I'm a bit down today.", 
    "Could be worse, could be better!", "I’ve been stressed.", "I'm doing fine!", 
    "It’s going well!", "Could be better.", "I'm feeling optimistic!", 
    "I'm surviving!", "It’s been a busy day!", "I'm having a good day!", 
    "I’m okay, thanks!", "I’m getting through the day!", "Feeling good today!", 
    "I’m alright!", "Not too shabby!", "I’m under the weather.", 
    "Today’s not my day.", "It’s going alright!", "I’ve been feeling low.", 
    "I’m in high spirits!", "I’m upbeat!", "Feeling a bit off.", 
    "I’m fine, nothing to complain about!", "I’ve been feeling better.", 
    "It's been a hectic day.", "It’s been an okay day.", "I’m full of energy!", 
    "Feeling a bit down.", "It's been a good day.", "I’m feeling neutral.", 
    "I’m exhausted!", "I’m feeling great today!", "I’m tired but alright.", 
    "I’m in a good space.", "I’m a little tired.", "I’m upbeat and positive.", 
    "It’s been a long day.", "I’ve had better times.", "I’m feeling refreshed!", 
    "I’m relaxed.", "I’ve had a tough time.", "I’m getting through.", 
    "I’m in a good place!", "I’m ready for anything!", "I’m feeling excited!", 
    "I’m feeling a little lost.", "Today is a great day!", "I’ve had a long day.", 
    "It’s been a chill day.", "I’m taking things slow.", "It’s been overwhelming.", 
    "I’m feeling accomplished.", "I’m doing as well as I can!", 
    "I’m feeling content.", "Today’s been rough.", "I’m motivated!", 
    "I’m feeling fine, thanks!", "It’s been a stressful day.", "I'm in a good mood.", 
    "I’m taking it easy today.", "I’m feeling positive about today!", 
    "I’m a bit stressed.", "It’s been smooth sailing.", "I’m exhausted, but okay.", 
    "I’m feeling hopeful.", "Today’s been tiring.", "I'm in a decent mood.", 
    "I'm doing alright!", "I'm feeling good about today.", "It's been busy but fine.", 
    "I'm doing okay, just tired.", "It's been a slow day.", "I'm feeling alright today.",
     "Have you seen any good movies lately?",
    "What's your favorite type of cuisine?",
    "How do you like to spend your weekends?",
    "What kind of music do you enjoy?",
    "Have you read any interesting books recently?",
    "What's your favorite hobby?",
    "Do you enjoy traveling? What's your favorite destination?",
    "What's your favorite way to relax?",
    "Have you tried any new restaurants lately?",
    "What's your favorite sport to watch or play?",
    "Do you prefer summer or winter? Why?",
    "What kind of pets do you like?",
    "Have you ever been to a concert?",
    "Do you enjoy cooking? What's your signature dish?",
    "What's the best trip you've ever taken?",
    "What's your favorite season of the year?",
    "Do you enjoy hiking or being outdoors?",
    "What's a skill you'd love to learn?",
    "Are you a morning person or a night owl?",
    "What's your favorite holiday tradition?",
    "Do you follow any sports teams?",
    "Have you ever been to a music festival?",
    "What's your favorite type of dessert?",
    "Do you like video games? What's your favorite one?",
    "What's the most interesting place you've ever visited?",
    "Do you enjoy any podcasts or audiobooks?",
    "What kind of movies do you like watching?",
    "Have you ever taken up a new hobby just for fun?",
    "Do you enjoy going to museums or art galleries?",
    "What's the last TV series you binge-watched?",
    "Do you prefer coffee or tea?",
    "What was your favorite subject in school?",
    "Are you interested in learning new languages?",
    "What's something you’ve always wanted to try but haven’t yet?",
    "What's your favorite way to exercise or stay active?",
    "Do you prefer reading fiction or non-fiction books?",
    "Have you ever participated in any community events?",
    "Do you enjoy gardening or growing plants?",
    "What's your go-to comfort food?",
    "Do you like to keep up with current events?",
    "What's the most adventurous thing you've ever done?",
    "Do you enjoy puzzles or brain games?",
    "What's your favorite way to spend time with friends?",
    "Do you collect anything as a hobby?",
    "What's your favorite type of art or creative expression?",
    "Have you ever done any volunteering work?",
    "Do you enjoy going to the theater or watching plays?",
    "Do you have any favorite podcasts or YouTube channels?",
    "What's the best piece of advice you've ever received?",
    "Have you ever tried meditation or yoga?",
    "Do you have any pets? What are their names?",
    "What kind of technology interests you the most?",
    "What's your favorite kind of weather?",
    "Are you interested in photography or taking pictures?",
    "What's your favorite memory from childhood?",
    "Have you ever taken a road trip?",
    "Do you enjoy board games or card games?",
    "What's the most challenging thing you've ever done?",
    "Do you prefer the beach or the mountains?",
    "What’s your favorite type of outdoor activity?",
    "What's your go-to snack when you're hungry?",
    "Have you ever been to a comedy show?",
    "What's your favorite way to stay organized?",
    "Do you enjoy attending social events or do you prefer quiet time?",
    "What's something you're really passionate about?",
    "Do you enjoy painting or drawing?",
    "Have you ever taken a cooking class?",
    "What’s the most interesting fact you know?",
    "Do you enjoy dancing? What type of dance?",
    "Have you ever gone camping or fishing?",
    "What's your favorite thing to do in your free time?",
    "What's the most unique food you've ever tried?",
    "Do you follow any particular diet or lifestyle?",
    "Have you ever visited a national park?",
    "What’s the funniest thing that ever happened to you?",
    "Do you like watching documentaries?",
    "What's the coolest technology you've seen recently?",
    "Have you ever been scuba diving or snorkeling?",
    "What's your favorite family tradition?",
    "Do you enjoy going to the gym or working out?",
    "What’s something you've learned recently?",
    "What kind of podcasts do you listen to?",
    "Do you like to plan or go with the flow?",
    "What's the best concert you've ever been to?",
    "Have you ever gone skydiving?",
    "What's your dream job?",
    "Have you ever done something that scared you?",
    "What's your favorite city to visit?",
    "What’s your go-to breakfast?",
    "Do you like to travel solo or with friends?",
    "What’s your favorite outdoor activity?",
    "Do you prefer watching movies at home or in theaters?",
    "Have you ever run a marathon?",
    "What's your favorite way to unwind after a long day?",
    "What’s the best gift you’ve ever received?",
    "Do you enjoy writing or journaling?",
    "Have you ever done any public speaking?",
    "What's your go-to app on your phone?",
    "Do you prefer spontaneous adventures or planned ones?",
    "What’s your favorite thing to do on a lazy day?",
    "Do you enjoy reading comics or graphic novels?",
    "What’s the best meal you’ve ever had?",
    "What kind of sports do you like to play?",
    "Do you enjoy solving riddles or puzzles?",
    "What's your favorite time of day?"
]

# Function to check for greetings
def is_greeting(user_input):
    user_input = user_input.lower()
    for greeting in user_hi:
        if greeting in user_input:
            return True
    return False


# Function to start the chatbot response
def start_chatbot_response(user_input):

    if is_greeting(user_input):
        return random.choice(Chatbot_hi)
    
    else: 
        return random.choice(general_answers)
    
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/get_response', methods=['POST'])
def get_response():
    user_input = request.json.get('message')
    bot_response = start_chatbot_response(user_input)
    return jsonify({'response': bot_response})

if __name__ == '__main__':
    app.run(debug =  True)

